### ISSUE TITLE
Change WU API URL to getMyTraffic.php

### ISSUE THREAD

**Issue by gwTumm** [h4llow3En/AGDSN_traffic_Mac#2]
getMyTrafficTest.php is now deprecated and the original getMyTraffic.php (rolling week model) has been replaced with the former getMyTrafficTest.php (credit model)

**Comment by h4llow3En** [comment]
included in release [v0.2.6](https://github.com/h4llow3En/AGDSN_traffic_Mac/releases/tag/v0.2.6)
