### ISSUE TITLE
Display notification when Traffic hits zero

### ISSUE THREAD

**Issue by JustusAdam** [h4llow3En/AGDSN_traffic_Mac#7]
In the event of all traffic being used up the internet connection will no longer be available. There should be an indication that this has happened, rather than just "normal" loss of connection or unavailability of the traffic information.

Suggestion is when the traffic gets extremely low (less than 1gb for instance) make a record of that including time and date. And upon subsequent connection loss check whether the traffic was unusually low and if that was the case display "No traffic left" instead of just nothing at all.

**Comment by kiliankoe** [comment]
So I guess you're also volunteering for testing this feature once it's implemented? :D

**Comment by h4llow3En** [comment]
I took a range of ca. 3gb.
