### ISSUE TITLE
Diskrepanz zur Webseite

### ISSUE THREAD

**Issue by kiliankoe** [h4llow3En/AGDSN_traffic_Mac#8]
Kurz nach 12 zeigt mir die App bereits meine 3 extra GB an, agdsn.de aber noch nicht. An und für sich würde ich auch je nach Sommer-/Winterzeit auch erst ein bis zwei Stunden später damit rechnen. Welche von beiden Quellen ist hier richtig?

**Comment by h4llow3En** [comment]
Da ich die Daten direkt vom Server bekomme, der den Traffic der Nutzer verwaltet, bin ich der Meinung, dass meins in diesem Fall richtig ist. Ich kann leider nicht all zu übel zu der Website sagen.
